### ISSUE TITLE
Implement "hide time while solving" feature

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#104]
If "Hide time while solving" is enabled:

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/edb43906-df7d-4830-bdf7-3f5c696c3b54)

Time should be replaced with a nice message: Solving

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/ea324887-4719-4f43-80b2-a671b222f7cd)

**Comment by abishek0057** [comment]
should there be only text "Solving" when "hide time while solving" feature is on or anything else, below is the preview with only "Solving" text

https://github.com/bryanlundberg/NexusTimer/assets/36365546/27706190-e1a9-4383-8eed-2d4d9b449ee6

**Comment by bryanlundberg** [comment]
That's absolutely right, we just require a larger responsive text size.
