### ISSUE TITLE
Create a toast component for alerts

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#107]
We are looking to design and create a toast component that integrates with our current style and enhances it. 

Mobile position:

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/9eeb9157-abd7-4908-809b-8f1aacf5a2f7)

Tablet or desktop computer with reasonable width dimensions:

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/80e100f7-f951-4bb8-814b-0671fbf7c5b5)

Here are the revised points:

- The toast should automatically disappear after 5 seconds.
- There should be an animation indicating the remaining time.
- Note that implementing it in the UI is not required at this stage, as triggers have not been developed yet.
- Need a close button X
- This toast component will serve various purposes, including alerting users about the best time, best average, unlocking new titles, cube deletions, and solve deletions, etc (Think about it).

Best design wins, we have time until create the triggers.

**Comment by KriteshTimsina** [comment]
Isn't there react-hot-toast or react-toastify library that serves this purposes .If you want something custom, would like to work on it.
