### ISSUE TITLE
Improving modal accessibility for close actions

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#108]
We need to do the process of closing modals easier for a better user experience. 

Click outside should close the modal.

SolveModal:

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/1ed061f1-cf7e-4df6-97e7-9de65560aca3)

CreateModal:

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/5f727f6a-45cb-444d-b383-1192ced25f36)

**Comment by abishek0057** [comment]
working on it

**Comment by bryanlundberg** [comment]
> working on it

ok!
