### ISSUE TITLE
Organizing component overload

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#109]
Our project contains too much spaghetti code, which hinders the full potential of Next.js and server components because we use the "use client" tag too early in pages due to the use of useState and useEffect. We need to improve organization and reduce components to its smallest size. Here's how to do it:

- Make a new issue related to the component you want to tidy up. Explain what needs fixing.
- When you are ready, create a pull request (PR) to implement the changes.

You can create a folder if you think can improve organization of the component.

If you are concerned about prop drilling, consider using Zustand to create a global state. It can help simplify data sharing across components. #72

**Comment by jonatfoodgroup** [comment]
Will take a look later this evening. I love some pruning and optimization of React code.

**Comment by bryanlundberg** [comment]
> Will take a look later this evening. I love some pruning and optimization of React code.

Great 😃

**Comment by jonatfoodgroup** [comment]
I went ahead and grabbed screenshots of the app started looking into code. Will get back into here tomorrow with some proposals as issues. Thanks!
<img width="721" alt="image" src="https://github.com/bryanlundberg/NexusTimer/assets/122066171/b28a2f9a-0c91-40a7-b561-dc252dc59424">
