### ISSUE TITLE
Not editable modal options

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#121]
The Modal for editing a cube: 
- "Category" should not be editable, only the name.

Changing the category from, for example, a 2x2 cube to a 7x7 cube can lead to skewed statistics. It's important to note that solves on a 2x2 cube are typically faster than those on a 7x7 cube. Therefore, altering the category may result in inaccurate best times, averages, and other statistical data.

This is not a bug; it's a deliberate design choice to ensure the integrity of your solving data.

**Comment by bryanlundberg** [comment]
![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/c138d424-3b00-498c-8a39-53adfc909d59)

**Comment by Adimaniac31** [comment]
hii,can you assign me this issue I would like to work on it.

**Comment by bryanlundberg** [comment]
Hello @Adimaniac31 you can work on it.

**Comment by Adimaniac31** [comment]
Thanks.

**Comment by Adimaniac31** [comment]
Hello,Can you look into the PR? And sorry I was late can you reassign me or merge the PR?

**Comment by bryanlundberg** [comment]
> Hello,Can you look into the PR? And sorry I was late can you reassign me or merge the PR?

no problem 👌

**Comment by Adimaniac31** [comment]
okay I will try to fix the error.

**Comment by Adimaniac31** [comment]
I solved the error, can you look into the PR?
