### ISSUE TITLE
modal before delete cube

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#122]
Create a confirmation modal that informs users of the number of solves to be deleted when they confirm the cube deletion. This action could potentially impact their personal best times.

**Comment by RKOsvk** [comment]
hello, can you assigne me for this issue?

**Comment by bryanlundberg** [comment]
@RKOsvk All yours

**Comment by Adimaniac31** [comment]
Hi, if both of you are fine. Can I work on it?

**Comment by bryanlundberg** [comment]
> Hi, if both of you are fine. Can I work on it?

Yes work on it please @Adimaniac31 👋

**Comment by Adimaniac31** [comment]
Hello, I have created the PR, can you look into it? Also, it was nice working with you it would be nice if we could connect on LinkedIn or something.
