### ISSUE TITLE
archive unique solves

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#123]
Right now its not possible archive single solves, need an extra option. To move the solve from session-solves to all-time-solves.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/9339a0cc-7140-42c0-98c7-7fd005a4a20e)

**Comment by zluipaiva** [comment]
hey, can i work on this one?

**Comment by bryanlundberg** [comment]
> hey, can i work on this one?

Yes you can. All yours
