### ISSUE TITLE
Add error handler using "import"

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#125]
Adding error handling for situations when the input file contains incorrect data. For now, a simple user alert should be sufficient and return the function before replace the localStorage.

**Comment by bryanlundberg** [comment]
Its here: 
![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/96246a72-3769-4043-9c1a-22d7bee3d887)

**Comment by sujithyadav998** [comment]
@bryanlundberg assign me this . I am interested to work on this .

**Comment by bryanlundberg** [comment]
@sujithyadav998 You can work on it. 👌

**Comment by harshkas4na** [comment]
hi @bryanlundberg  , can i work on this too?

**Comment by bryanlundberg** [comment]
> hi @bryanlundberg , can i work on this too?

Hi, @harshkas4na no updates on the issue, please go ahead and work on it. It's assigned to you.

**Comment by harshkas4na** [comment]
can you please check it fast , so I can get it merge atleast before 31 please.
