### ISSUE TITLE
 Synchronize the selected cube after deleting it

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#129]
If you've chosen the "X" cube and decide to delete it, it remains selected on the Timer page. It should be reset to a null state until you select a new cube just in case you deleted the selected cube.

**Comment by zluipaiva** [comment]
Hello, i would like to work on this issue

**Comment by bryanlundberg** [comment]
> Hello, i would like to work on this issue

Hi @zluipaiva you can. Thanks
