### ISSUE TITLE
Inaccurate pyramid image representation

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#134]
Need create a  new image 

current pyramid 2x2: 
![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/cdb74659-29c7-4923-847e-99f43c52f29d)

correct pyramid 3x3:
![png-transparent-pyraminx-rubik-s-cube-jigsaw-puzzles-combination-puzzle-cube-pyraminx-rubik-s-cube-jigsaw-puzzles](https://github.com/bryanlundberg/NexusTimer/assets/119996547/1b82aa6d-3656-4bd3-8e15-1789d9f55fbe)

**Comment by NUMS-half** [comment]
@bryanlundberg Could you please assign this problem to me?

**Comment by bryanlundberg** [comment]
> @bryanlundberg Could you please assign this problem to me?

Sure, you can work on it,

**Comment by NUMS-half** [comment]
Thank you!!!
