### ISSUE TITLE
Add Data Validation using the 'Import' feature

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#144]
File: [importDataFromFile.ts](https://github.com/bryanlundberg/NexusTimer/blob/main/src/lib/importDataFromFile.ts) has everything needed to handle error using import feature.

Now, it is necessary to finish it, there is a function inside `isValidCubesData()`, which should return 'true' or 'false' based on whether all the data in the imported .txt file complies with our designated data structure.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/0b936fb4-66ef-4ed8-994d-daf31ea94795)

**Comment by AnuMessi10** [comment]
Hi @bryanlundberg, I am new to this and would like to contribute, let me know if you can assign this to me. Cheers!

**Comment by bryanlundberg** [comment]
> Hi @bryanlundberg, I am new to this and would like to contribute, let me know if you can assign this to me. Cheers!

Welcome, you can work on it. 👋
@AnuMessi10

**Comment by bryanlundberg** [comment]
@AnuMessi10 could you please confirm if you're currently working on this?

**Comment by AnuMessi10** [comment]
Hi @bryanlundberg, yes I am working on it, have made a fix as well, just testing some border cases
