### ISSUE TITLE
Scramble do not show when solve is opened twice

### ISSUE THREAD

**Issue by zluipaiva** [bryanlundberg/NexusTimer#147]
In /solves page, when a solve is opened twice in a row the scramble image is not shown on the second time

![image](https://github.com/bryanlundberg/NexusTimer/assets/23319971/3bb6a61d-23cf-41ae-9a4d-9a6be1d6bf86)

**Comment by bryanlundberg** [comment]
I've noticed it too, but I'm not sure why at the moment.

**Comment by bryanlundberg** [comment]
Would you like take care of that approach?

@zluipaiva

**Comment by zluipaiva** [comment]
yes!
