### ISSUE TITLE
Not updating selected cube name after edit

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#163]
If you modify the cube name of the current selected cube, the updated name is reflected in the system, but the displayed name remains unchanged.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/b891643c-6cc0-4ffc-8817-3db7d04f5586)

**Comment by rohan0124** [comment]
Can you add further details when the name is not updating
I tried to update the cube name and it is reflecting correctly

**Comment by bryanlundberg** [comment]
Here i'm showing the issue visually @rohan0124 

https://github.com/bryanlundberg/NexusTimer/assets/119996547/d97fa7e7-b7c6-4ea0-93a2-899e3f62ec66
