### ISSUE TITLE
Add text alert for average records

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#176]
we can improve the record alert including a small text.

1. Need include translations
2. Need to use the boolean from menu settings "alert - best average"

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/4a1a82b2-6007-4e6c-b499-0a2f2b30839d)

**Comment by rsharvesh16** [comment]
@bryanlundberg  Do we need to change from New Best Average to "alert - best average"? Wright? I am not getting the issue correctly.

**Comment by bryanlundberg** [comment]
Hey @rsharvesh16 just need to add the message "New best average" like in the pic when the user beat a new average time.

"Alert - best average" its a boolean from settings.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/c9ee1e78-9660-41a3-9c5f-2f014598ef23)

You can find that setting in the global state store at store/SettingsModalStore.ts
