### ISSUE TITLE
Add text message beating personal best time

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#177]
we can improve the record alert including a legend.

1. Need include translations
2. Need to use the boolean from menu settings "alert - best time"

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/82ac683a-8812-4f34-b1f7-8e140f146312)

**Comment by idrak888** [comment]
Hi I am interested in working on this

**Comment by bryanlundberg** [comment]
Sure, go ahead you can start 
@idrak888

**Comment by idrak888** [comment]
Could you point me to the right file for this. Not sure where the 'new record message' is currently handled/rendered

**Comment by bryanlundberg** [comment]
Actually it is not rendered, doesn't exist in the app. That's the mission, create a good place to insert the text message.

If you mean where is the logic launched after doing a best time. hooks/useTimerStatistics

Doing like this you can get the overall record calculation from selected cube category.

 const { global } = useTimerStatistics()

From hooks/useTimerStore
const { lastSolve } = useTimerStore()
This one has the last resolution details including time.


Finally in the place you want render the message make a boolean

global.best === lastSolve.time

If true message will be "congratulations...etc"

**Comment by idrak888** [comment]
I have decided that HeaderTimer.tsx, right under the scramble display, would be a suitable place for the text. I did as you said  and utilized the useTimerStore() and useTimerStatistics() to conditionally render the time like so:

![image](https://github.com/bryanlundberg/NexusTimer/assets/29671239/48d04c43-a1f5-4a58-8103-342398b3576a)

**Comment by bryanlundberg** [comment]
I will review it there, thanks!
