### ISSUE TITLE
Add alert "worst time"

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#190]
We need create the logic to identify the worst time and render a message. And finally link the functionality with the menu settings.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/f52996b1-4976-4387-9f9f-ca5efee84d6b)

**Comment by MishraRohan** [comment]
I am interested to work on this issue. This is my first issue. My approach is to create logic for CalWorsttime.ts  looking at the CalBesttime.ts, and try to link it wherever CalBesttime.ts is linked.

**Comment by bryanlundberg** [comment]
> I am interested to work on this issue. This is my first issue. My approach is to create logic for CalWorsttime.ts looking at the CalBesttime.ts, and try to link it wherever CalBesttime.ts is linked.

Hi @MishraRohan your help is welcome!

This task can be easily executed sorting the global solves array by prop `time`and saving the value of the worst it in a variable called `globalWorstTime`.

you can get last solve data from anywhere as:

`const {lastSolve} = useTimerStore();`

then
`lastSolve.time` === `globalWorstTime` // render

Message must be render in the same spot used for "Best average alert", of course display priority would be for average.

TimerWidgets.tsx

**Comment by bryanlundberg** [comment]
Remember update the repository, today I made a big update.

**Comment by MishraRohan** [comment]
Hi Bryan, I was travelling back to college so i could spend time on this,
i will be in touch with you now
 when i started working on this i found these issues
import { create } from "zustand";
in /src/store/timerStore.ts
What is zustand?
the file was not able to understand this.
will this problem affect the worstTime calculation.?

**Comment by bryanlundberg** [comment]
Zustand creates global states available to all components; I don't think you need to modify or create a global state for this task.
