### ISSUE TITLE
Incorrect Calculation in AoX (Average over X)

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#194]
Currently, the calculation method for AoX in our statistics is using a simple average. However, the correct approach involves excluding the highest and lowest values before calculating the average.

It's important to note that this adjustment should only be applied to AoX, and we should maintain the normal average calculation for all other metrics.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/9c4fdbab-70f9-41c6-a3a1-8aada3f15625)

**Comment by lucasfirmo62** [comment]
Hi, I'm interested in this issue, could you explain the problem better so I can try to resolve it?

**Comment by bryanlundberg** [comment]
Hi @lucasfirmo62, for this issue the problem basically on the formula.

For Ao3,5,12,50,100,1000 statistics: instead of doing a simple average calculation, the correct implementation for an Ao its before calculate the overall average remove the best and worst time.

I would like also keep the standard average, we would need add to the chart values named as: Avg3,5,12,50,100,1000
