### ISSUE TITLE
Eliminate negative scale from chart

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#201]
negative solving times should not be displayed on the chart.

Scale should be from 0 and above

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/59cd4b31-0b84-414d-8eb3-255d48be8778)

**Comment by AnuMessi10** [comment]
Hello @bryanlundberg, its me again, let me know if you can assign this to me. Cheers!

**Comment by bryanlundberg** [comment]
> Hello @bryanlundberg, its me again, let me know if you can assign this to me. Cheers!

Hi, all yours! 👋
