### ISSUE TITLE
Fullscreen feature

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#202]
Would be a good detail include a button to easily go to fullscreen mode:

Consider adding 2 version of icon, to enter and exit.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/dcabd80d-54f6-4e33-a032-cfd1142ab277)

**Comment by RigvedRocks** [comment]
Hi @bryanlundberg I have added a draft PR which pertains to this feature please have a look at it and suggest amends if any.
