### ISSUE TITLE
validate unique cube name before submit

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#204]
Right now there is an issue, its possible create cubes with the same name.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/561d31f8-d002-4fc3-8159-1ca0ba967b77)

Would be correct, only allow unique names.

Consider adding an alert to the user "Name in use" or something similar in the modal and also for editing name...

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/a644fd9e-8ac5-476f-a25d-9a21bd3ea37e)

**Comment by Ganesh107** [comment]
can i work on this?

**Comment by bryanlundberg** [comment]
> can i work on this?

Yes you can! Just remember update the repository before work on it👋
