### ISSUE TITLE
style solves button

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#222]
buttons should have a disabled status and appearance when there is not a cube selected or there is not solves to display

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/2fecaafd-c57e-4902-a18d-d94d26bc737d)

**Comment by Ganesh107** [comment]
can i work on this?

**Comment by bryanlundberg** [comment]
> can i work on this?

I haven't initiated this task yet, so feel free to go ahead and take care of it. @Ganesh107  👋

**Comment by bryanlundberg** [comment]
You can take the :hover colors as reference, looks pretty good for the job.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/bd25adbf-f929-4826-9a87-b5dbcbd02905)

**Comment by Ganesh107** [comment]
Thanks for assigning me I'll work on it

**Comment by Ganesh107** [comment]
![Screenshot (13)](https://github.com/bryanlundberg/NexusTimer/assets/78807238/1dcb2824-e2ac-45fd-9105-3b905eb39105)
should I disable hover?

**Comment by Ganesh107** [comment]
![btn_fix](https://github.com/bryanlundberg/NexusTimer/assets/78807238/2cb6e802-c89e-4f4f-a140-af94e1cefb28)
is this the right way ,should i disable the hover?

**Comment by bryanlundberg** [comment]
> ![btn_fix](https://private-user-images.githubusercontent.com/78807238/293381515-2cb6e802-c89e-4f4f-a140-af94e1cefb28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjExMjAsIm5iZiI6MTcwMzg2MDgyMCwicGF0aCI6Ii83ODgwNzIzOC8yOTMzODE1MTUtMmNiNmU4MDItYzg5ZS00ZjRmLWExNDAtYWY5NGUxY2VmYjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE0NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMWE4NGY1MjM3YTYxNWNkZTgyYzBhZTZjNzUzZmRhYzg3NjVlODY5ZTU3NzA1NTZmZDJjYzlhN2U5ZTU4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.An7PxS92OxhI5f1v1mwVBSGV7ijejjwtMxGEF7b_26U) is this the right way ,should i disable the hover?

In appearance looks very good, just ensure that it functions as a disabled button 😅

**Comment by Ganesh107** [comment]
I have disabled functionality of the buttons also when the nothing is selected from select box
