### ISSUE TITLE
improve "modal solve" responsive

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#247]
In certain instances, when utilizing large cubes, the scramble becomes excessively lengthy, causing the modal to overflow.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/8498e085-86a1-4c93-a1f7-a69d4e63fa1c)

**Comment by shaurya5** [comment]
Hi Bryan. What if the menu div is rendered upwards instead of downwards?

**Comment by bryanlundberg** [comment]
i gree, could be position upward only if does not fit down. (responsive) 👍
