### ISSUE TITLE
custom menu context

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#270]
Right-click should display a submenu with quick action options

- Active "solve" should change border color for better UX.
- Submenu should be fixed down,  width 100% of "solve" size. (Fits better instead using right click x,y position state)

sample:
![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/39bf7a06-e7df-4da9-a1f5-425d2ffe04a3)

**Comment by syrok94** [comment]
Hii @bryanlundberg, I would love to work on this issue. will you assign this task to me?

**Comment by bryanlundberg** [comment]
> Hii @bryanlundberg, I would love to work on this issue. will you assign this task to me?

Your help is welcome, all yours 👌

**Comment by bryanlundberg** [comment]
@syrok94 updated the task requirements 👋

**Comment by syrok94** [comment]
> @syrok94 updated the task requirements 👋

Sure @bryanlundberg , will look into the requirements and work accordingly

**Comment by syrok94** [comment]
Hi @bryanlundberg, can you please verify if this behavior of the context menu is valid? 
As you can see in the second image when I click on some of the last solves , it hides and will be visible on scrolling down.

![nexus4](https://github.com/bryanlundberg/NexusTimer/assets/58144335/11e084ea-cbb3-4e75-b82b-98e7220ed03b)
![nexus5](https://github.com/bryanlundberg/NexusTimer/assets/58144335/4fb9e288-e221-4c4a-8b4b-7eb943908d93)

**Comment by bryanlundberg** [comment]
> o

Should not hide 😉
