### ISSUE TITLE
sort solves section by (date,penalty, time)

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#286]
Feature for `solves` page.

- Add a dropdown menu to sort the historical list of solves.

-sort by: date (oldest, newest), +2, fastest, slowest, etc....

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/cab28a10-472b-4afe-aa96-3964c122139a)

**Comment by syrok94** [comment]
hii @bryanlundberg assign this to me

**Comment by bryanlundberg** [comment]
@syrok94 Assigned. Let me know if you have any doubts in the process👌

**Comment by syrok94** [comment]
yeah sure
