### ISSUE TITLE
Adapting date formats for internationalization using locales

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#318]
Currently, dates are displayed in a basic format following the U.S. calendar. We need to change all these sections to be adjusted using locales.

Its possible get current Locale using the hook 

`const locale = useLocale()`

Search what fits better: `fns` `moment` or `luxon`

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/48f9a1a3-8245-4ff5-8757-1495b61d0642)

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/b587a8be-9396-4434-86f5-0f436e7052e9)

**Comment by syrok94** [comment]
Hii @bryanlundberg , assign this to me

**Comment by bryanlundberg** [comment]
> Hii @bryanlundberg , assign this to me

All yours, thanks!
