### ISSUE TITLE
feat: implementing a dropdown option for sharing solves session

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#324]
It is necessary to create a dropdown option on the "solves page" with the following options:

- last ao5
- last ao12
- all session

Clicking an option should copy the following format to the clipboard:

> Generated by NexusTimer:  2024-06-29
> Avg of 5: 1.64
> 
> List of times:
> (2.01)   R' U L U' B' U' B U' l r' b
> (1.39)   L' B L' R' U' B' R' L' r
> 1.55   U' R' U' R B L B' L' b' u'
> 1.53   R' U' B' R B R' U' L u'
> 1.84   R L' U' B L U' R' L l' b u'

Please note:

The best and worst times must be enclosed in parentheses ().

**Comment by syrok94** [comment]
Hii  @bryanlundberg, please assign this to me and let me know if there is some specific icon you want to add to it.

also, let me know where you want to place this dropdown?  It will be helpful if you specify the required design.

**Comment by bryanlundberg** [comment]
Hi, @syrok94 ,

The design idea is as follows:

We can enhance the current sort menu and extend its functionality while maintaining a simple UI.

![image](https://github.com/user-attachments/assets/3d5bcb2d-d769-4346-a968-aeb4ee313ad0)

We can start with basic AO5 and AO12.

![image](https://github.com/user-attachments/assets/0ab95b08-b90b-4216-9631-171877f0960b)


👋
