### ISSUE TITLE
Automatically create a default cubes upon first app launch

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#327]
It's essential to create a default cube template to streamline the onboarding process for new users.

example:

> Name: template-cube-333
> Name: template-cube-444
> Name: template-cube-555

categories: 222, 333, 444 ,555, 666, 777, megaminx, sq1

**Comment by Sauhard74** [comment]
hey can i work on this issue? i would like to contribute to this repo ,it would be great if you assign it to me

**Comment by bryanlundberg** [comment]
> hey can i work on this issue? i would like to contribute to this repo ,it would be great if you assign it to me

Hi @Sauhard74, your help is welcome!

**Comment by bryanlundberg** [comment]
@Sauhard74 has there been any progress?
