### ISSUE TITLE
Customizable default starting cube selection

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#328]
We need a new feature to allow users to customize the startup process. It's repetitive to manually select the same starting cube every time you access the application.

- Select a default starting cube

This implementation require:

- Add a section on Settings named "Preferences"
- Add basic translation fallback "english" at least for labels
- Attach the required logic

**Comment by myheadisempty** [comment]
Hi,
I'd like to take a shot at implementing this feature.
Thanks.

**Comment by bryanlundberg** [comment]
> Hi, I'd like to take a shot at implementing this feature. Thanks.

Hi @myheadisempty , all yours! Tell me if you need something 👌

**Comment by myheadisempty** [comment]
Hi, I have a question. When the page loads, if a default cube is set, operations should occur as if the cube were selected manually (I mean setting the state with setSelectedCube(defaultCube) and generating a new scramble).

**Comment by bryanlundberg** [comment]
> Hi, I have a question. When the page loads, if a default cube is set, operations should occur as if the cube were selected manually (I mean setting the state with setSelectedCube(defaultCube) and generating a new scramble).

Yes, that's the intention 👌

**Comment by myheadisempty** [comment]
Thank you for the issue, I was glad to help!
