### ISSUE TITLE
Force cube name change when cube category is modified

### ISSUE THREAD

**Issue by davideperez** [bryanlundberg/NexusTimer#343]
PROBLEMA: En https://www.nexustimer.pro/cubes, al editar un cubo, al cambiar el tipo de cubo, obliga a cambiar el nombre del cubo. 

SOLUCION: Deberia dejar cambiar el tipo de cubo y poder conservar el mismo nombre.

**Comment by bryanlundberg** [comment]
Te asigno la issue, avísame si tienes dudas como abordar los cambios necesarios.
Buena suerte david.
