### ISSUE TITLE
Persistent errors in edit/delete cube dialogs

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#345]
Persistent errors in edit/delete cube dialogs. Errors remain after reopening, causing confusion, especially when interacting with different cubes.

![image](https://github.com/user-attachments/assets/a7e6279f-b358-42a9-8f1e-b41ebcb13b9f)

![image](https://github.com/user-attachments/assets/eaa42f39-8971-4dbb-aee1-6ff0183e3de8)

Solution, just a simple reset of state when it closes.

**Comment by syrok94** [comment]
hey @bryanlundberg can I work on this issue?

**Comment by bryanlundberg** [comment]
> hey @bryanlundberg can I work on this issue?

Hi @syrok94 all yours! Thanks
