### ISSUE TITLE
add remote backup

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#362]
Basic idea (Asynchronous - not real time sync)
![image](https://github.com/user-attachments/assets/643873e6-5091-4c89-95b5-fda3a2f61d5c)

related task
#363 (google auth)
#364 (rework for a bigger navbar, to allow new tabs as profile, register, login, competitive matches, trainer, etc...)

**Comment by myheadisempty** [comment]
Hello, are you planning to use Mongo directly in Next?

**Comment by bryanlundberg** [comment]
> Hello, are you planning to use Mongo directly in Next?

Atm, yes ORM (mongoose). As it won't be working in real time, the data. I was planning instead an API, just use server actions.

Likewise, I'm open to suggestions, what do you think?
