### ISSUE TITLE
Undo action for deleting a solve

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#376]
We need to slow down the delete "sonner" to 2 sec. And implement an undo button, to restore the solve in case a missclick.

![1730580389205.png](https://github.com/user-attachments/assets/4aa9b313-76c8-4d2d-994d-3402d3ea707c)

**Comment by syrok94** [comment]
Hey @bryanlundberg , I would like to contribute please assign this to me .

**Comment by bryanlundberg** [comment]
> Hey @bryanlundberg , I would like to contribute please assign this to me .

All yours! @syrok94
