### ISSUE TITLE
style: wrong background color import modal

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#383]
only visible in light mode

![image](https://github.com/user-attachments/assets/bdbe19ec-216d-4d7c-bffa-6663a3721b9a)

**Comment by NguyenTranThanhTu** [comment]
hello, can i help you with this issue

**Comment by bryanlundberg** [comment]
> hello, can i help you with this issue

Hi, @NguyenTranThanhTu won't be possible, there's a PR open for this 😔
