### ISSUE TITLE
Improve current language translations

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#52]
This issue is dedicated to improving language translations for our project. We need to either add new translations for missing languages or fix existing translations that may have errors or inconsistencies.

Its important for me reach a closer meaning but related to the thematic if that involve the use of other words

**Comment by bryanlundberg** [comment]
File location [src/app/translations](https://github.com/bryanlundberg/NexusTimer/blob/main/src/translations/global.json)

**Comment by HpatricioH** [comment]
I see that this translation into Spanish has been mixed with English. I can add the correct word, could you assign this to me please?

![image](https://github.com/bryanlundberg/NexusTimer/assets/59483053/e4516b3c-f4d3-4eb8-87ba-136ce7cd2db1)

**Comment by bryanlundberg** [comment]
> I see that this translation into Spanish has been mixed with English. I can add the correct word, could you assign this to me please?
> 
> ![image](https://github.com/bryanlundberg/NexusTimer/assets/59483053/e4516b3c-f4d3-4eb8-87ba-136ce7cd2db1)
> 

Hi, yes you can improve it, just open a new issue. 👋
