### ISSUE TITLE
Feature Import / Export  user data

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#54]
We need to enhance the user experience by adding a feature in the menu settings that facilitates the export and import of user data. This feature will be especially valuable until we implement backend solutions for data management.

**Comment by bryanlundberg** [comment]
Export: should be done, writing all localStorage "cubes" inside a .txt file.

**Comment by bryanlundberg** [comment]
Import: Read the .txt file and replace localStorage "cubes"

**Comment by CarlosCRG19** [comment]
Hey @bryanlundberg can you assign me this issue?

**Comment by bryanlundberg** [comment]
> Hey @bryanlundberg can you assign me this issue?

Hey @CarlosCRG19 all yours 👌

**Comment by bryanlundberg** [comment]
Hi @CarlosCRG19, have you made any progress or improvements recently?
