### ISSUE TITLE
CSS Fix Required for modal displaying solve details

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#70]
The current modal displaying solve details is not covering the screen properly, and this issue persists in both desktop and mobile views. The blur only covers half of the name

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/1a772078-885f-4fe5-a250-a8f3d32fc970)

**Comment by abishek0057** [comment]
Can I have this assigned to me? and can you explain how this model should look?

**Comment by bryanlundberg** [comment]
> Can I have this assigned to me? and can you explain how this model should look?

Hi @abishek0057 , the blur effect should cover the entire screen, but doing a closer inspection to the bottom of the page, it isn't currently happening.

**Comment by abishek0057** [comment]
@bryanlundberg add cube modal also have the same blur issue
![image](https://github.com/bryanlundberg/NexusTimer/assets/36365546/ab27464f-9da7-46d2-af34-c68d43f7e2fa)
