### ISSUE TITLE
Add shortcut to cube selection

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#77]
In case you click cube details redirect to timer page and also set the selected cube with the previously clicked, should not be trigger with the edit column.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/d3968b48-8bec-4464-bc65-7917e988521f)

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/a46e9057-4860-4521-916e-51f32819e4fb)

**Comment by KriteshTimsina** [comment]
working on it!
