### ISSUE TITLE
Time Display Formatting

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#79]
We got a new function for formatting time in a nice way. As a result, we need update all existing components to utilize this function before rendering.

- Timer (desviation, mean, best, ao5 - ao100)
- Solves (session / all, solve modal)
- Metrics (Last activity, all category statistics...)

[formatTime.ts](https://github.com/bryanlundberg/NexusTimer/blob/main/src/lib/formatTime.ts)

**Comment by abishek0057** [comment]
value of deviation, mean, best and all category statistics are return in second but `formatTime` function receive time in millisecond, should `formatTime` be use in these cases too with `formatTime(val*1000)` to convert value back to millisecond or leave it as it is?

**Comment by bryanlundberg** [comment]
> value of deviation, mean, best and all category statistics are return in second but `formatTime` function receive time in millisecond, should `formatTime` be use in these cases too with `formatTime(val*1000)` to convert value back to millisecond or leave it as it is?

I believe will be better remove the parts that previously uses seconds and work everything in ms, solve times are naturally in ms. The mission is remove all useless conversions are directly ms  -> `formatTime`. 

@abishek0057
