### ISSUE TITLE
Manual mode negative numbers

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#91]
The timer should not accept negative values, as dates can not be negative.

**Comment by diwash007** [comment]
Can you please elaborate?

**Comment by bryanlundberg** [comment]
@diwash007 

You should not allow the plus and minus signs to be written in the input fields, only numbers
![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/f9b2de8e-4e5d-4a8b-a67a-49cad32a7ff6)
